/** Authored presentation strings. Keys remain the canonical simulation language. */
export const UI_EN: Record<string,string> = {
'雾':'FOG','雾港生活':'Fog Harbor','说过的话，做过的事，都会留下痕迹。':'Your words and actions leave a trace.',
'保存':'Save','生存状态':'Survival status','雾港游戏地图':'Fog Harbor game map','雾港 · 老街区':'Fog Harbor · Old Quarter','背包':'Bag','档案 / 手记':'People / Journal','? 操作':'? Guide',
'当前交谈':'Current conversation','场景交互':'Nearby interaction','二十元，':'Twenty yuan.','从今天过下去。':'Make a life, starting today.',
'先往东北走，到晚风茶馆接一份外卖。':'Head northeast to Evening Breeze Teahouse for a delivery job.',
'取餐、送到、交付，赚到你的第一笔生活费。':'Pick up the meal, find the customer, and hand it over to earn your first pay.',
'饿了吃东西，累了歇脚。街坊会记住你。':'Eat when hungry. Rest when tired. Your neighbors will remember you.',
'移动':'Move','交谈 / 地点':'Talk / Place','继续在雾港的生活':'Continue your life in Fog Harbor','开始第一天':'Start day one',
'先活到第三天，完成三次配送。然后，生活继续。':'Reach day three and complete three deliveries. Then life goes on.',
'世界已暂停':'World paused','时间、体力和订单都暂停，点击「继续」返回。':'Time, energy, and delivery timers are paused. Choose Resume to return.',
'这次没能撑下去。':'This time, you did not make it.','重新开始':'Start again','保存这段经历':'Export this chapter','角色档案与记录':'People and records','雾港档案':'Fog Harbor records','关闭档案':'Close records','关闭':'Close','侧栏':'Sidebar','生活':'Life','人物':'People','手记':'Journal','记录':'Records',
'/ 方向键 移动 ·':'/ Arrow keys to move ·','跑步 ·':'Run ·','交谈 / 地点 ·':'Talk / Place ·','已恢复本机存档':'Local save restored','每 15 秒自动保存':'Autosaves every 15 seconds',
'先照顾自己，再认识街坊。':'Look after yourself. Get to know your neighbors.',
'WASD / 方向键移动，也可以点击地面行走；Shift 跑步，E 打开身旁的居民或地点。也可以点击居民。右上小地图的金点是当前目的地。':'Move with WASD or arrow keys, or click the ground. Hold Shift to run. Press E to interact with a nearby resident or place, or click a resident. The gold dot on the upper-right minimap marks your destination.',
'第一单：到晚风茶馆门口，按 E 接单，等待 6 秒取餐。送到金色标记，走近收件人，在画面下方的交谈选项中点击交付。只有实际交付才会结算。迟到或餐凉后，可以解释并交付；对方决定全款、减款还是拒收。':'First delivery: go to Evening Breeze Teahouse, press E to accept an order, and wait 6 seconds to pick it up. Follow the gold marker to the customer, approach them, and choose the delivery option below. Payment happens only after handover. If late or cold, explain and deliver; the customer may pay in full, reduce payment, or refuse.',
'按 B 打开背包，买来的食物点击「吃用」。广场、临水亭可免费休息；小院住宿 12 元恢复体力和健康；没钱时去驿站做 18 秒短工挣 12 元。工作中可以中止，但没有报酬。':'Press B to open your bag and choose Eat to use purchased food. Rest free at the plaza or Riverside Pavilion. Lodging costs ¥12 and restores energy and health. If short of money, work for 18 seconds at the post station to earn ¥12. You may cancel work, but receive no pay.',
'一天为 6 分钟。饱腹耗尽会损失健康，体力低会走得慢。走近居民按 E 或点击居民交谈时，世界暂停；读完回复后点击「结束交谈」或按 Esc，再恢复探索。帮忙等计时活动也在结束交谈后开始。隐藏游戏页面、打开说明或手动暂停时，时间停止。第三天且完成三单即站稳脚跟，之后继续生活。':'A day lasts 6 minutes. An empty fullness meter costs health; low energy slows you down. Talking pauses the world. Choose End conversation or press Esc to resume exploring. Timed help begins after the conversation ends. Time also stops when the page is hidden, this guide is open, or you pause manually. Reach day three with three deliveries to establish yourself, then keep living.',
'动作和回应意图由 Jev 选择，台词为预写表达。角色会保留经历、信任和履约记录。记录页明确区分真实 Jev 与规则演示。':'Jev chooses actions and response intentions; dialogue is authored. Characters retain experiences, trust, and promise records. Records distinguish real Jev decisions from the rules demo.',
'回到街区':'Return to the neighborhood','重新开始一段生活？':'Start a new life?','当前存档将被替换。可先到记录页导出经历。':'Your current save will be replaced. You can export your history from Records first.','留在这里':'Stay here',
'打算':'Planning','进行中':'In progress','等候':'Waiting','已完成':'Completed','已打断':'Interrupted','约定中':'Active promise','已履行':'Fulfilled','已失约':'Broken',
'谨慎、重承诺。可靠的工作比空话更能赢得他的信任。':'Cautious and true to his word. Reliable work earns his trust more than empty talk.',
'好奇而宽容。诚实解释一次失误，她往往愿意理解。':'Curious and forgiving. An honest explanation of a mistake often earns her understanding.',
'讲究实际的生意人。看重付出的劳动和清楚的约定。':'A practical businesswoman who values real effort and clear agreements.',
'忙碌的送信人，很看重准时。屡次耽误会让他失去耐心。':'A busy courier who values punctuality. Repeated delays wear down his patience.',
'耐心的老街坊。关照邻居，也记得谁曾说到做到。':'A patient old neighbor who looks after others and remembers who keeps their word.',
'进度已保存在本机。':'Progress saved on this device.','存档失败，请导出经历':'Save failed; please export your history','浏览器无法保存，请在记录页导出。':'The browser cannot save. Export your history from Records.',
'就在附近':'Nearby','西':'West','东':'East','北':'North','南':'South','西北':'Northwest','东北':'Northeast','西南':'Southwest','东南':'Southeast',
'下一份订单即将到来。':'The next order will arrive soon.','取走这份餐品':'Pick up this meal','热饭 · 14 元 / 饱腹 +65':'Hot meal · ¥14 / Fullness +65','热茶 · 5 元 / 体力 +20':'Hot tea · ¥5 / Energy +20','面包 · 8 元 / 饱腹 +35':'Bread · ¥8 / Fullness +35','住宿 · 12 元 / 25 秒':'Lodging · ¥12 / 25 seconds','搬运短工 · 18 秒挣 12 元':'Hauling job · 18 seconds for ¥12','长椅休息 · 免费 / 12 秒恢复 28 体力':'Rest on a bench · Free / 12 seconds for 28 energy',
'正在做的事':'Current activity','中止活动（无报酬，已付费用不退）':'Cancel activity (no pay or refund)','走近店铺门口，按 E 查看服务。':'Approach a shop entrance and press E for services.','服务期间世界继续运转；关闭面板后可移动。':'The world keeps moving during services. Close this panel to move.',
'随身食物':'Food in your bag','没有吃的了。茶馆卖热饭，杂货铺卖面包。':'No food left. The teahouse sells meals; the general store sells bread.','待送餐品':'Meal for delivery','没有其他随身物品。':'No other items.','今天，也要好好过。':'Make today a good day.',
'你已在雾港站稳脚跟。继续送单、结识街坊，过自己的日子。':'You have found your feet in Fog Harbor. Keep delivering, meeting neighbors, and living your life.','手里的约定':'Your current promise','第一步 / 下一份生活费':'First step / Next earnings','接单':'Accept','取餐':'Pick up','交付':'Deliver','生活地图':'Neighborhood services','接单 / 取餐 / 热饭与茶':'Orders / Pickup / Meals and tea','买面包 · 8 元':'Bread · ¥8','住宿 · 12 元':'Lodging · ¥12','短工 · 挣 12 元':'Temporary work · Earn ¥12','免费休息':'Free rest',
'饱腹':'Fullness','体力':'Energy','社交满足':'Social satisfaction','事务压力':'Work pressure','个人打算进展':'Personal goal progress','角色需求与行动预期':'Needs and action forecasts','生活中的牵挂':'What matters today','迫切':'Urgent','在意':'Concerned','尚可':'Manageable','可选活动预估 · 含步行与活动时间':'Activity estimates · Travel and work time included','个人打算 +1 次':'Personal goal +1','显示部分可行选择及预计直接效果；角色实际选择和最终变化以行动记录为准。':'Some available choices and expected direct effects. See action records for actual choices and outcomes.',
'正在完成手上的活动，完成后再作打算。':'Finishing the current activity before deciding what comes next.','先守住与你的送餐约定。':'Keeping your delivery agreement first.','正在等待下一次行动机会。':'Waiting for the next chance to act.',
'当前认知':'Current belief','消息冲突':'Conflicting reports','需要确认':'Needs confirmation','尚不清楚':'Unknown','角色认知':'Character knowledge','· 调试视图':'· Debug view','这是角色掌握的信息，不代表世界真相，也不代表玩家已获知。':'This is what the character knows. It may differ from the truth and from what the player knows.','玩家':'Player','背景常识':'Background knowledge','亲眼观察':'Observed firsthand','自己的经历':'Personal experience','旧存档记录，来源未记录':'Legacy record; source unknown','迁移记录':'Migrated record','获知':'Learned','已过有效期':'Expired','已被后续证据替代':'Superseded by later evidence','暂时没有结构化知识记录。':'No structured knowledge recorded yet.',
'对你的信任':'Trust in you','就在身旁':'Beside you','渐渐信赖':'Growing trust','有所戒备':'Wary','正在认识':'Getting acquainted','此刻':'Right now','正在斟酌你的话':'Considering your words','正在安排自己的下一步':'Planning the next step','走近居民，在地图上点击或按 E 交谈。':'Approach a resident, then click them or press E to talk.','记住的经历':'Remembered experiences','尚未有共同经历。':'No shared experiences yet.','你们的约定':'Your promises','送餐到约定地点，验收后付款':'Deliver to the agreed place; payment follows acceptance',
'个人打算与心情':'Personal goals and feelings','自己的生活':'A life of their own','角色档案视图；这些内容不等于已经向玩家说出口。':'Character profile: these details may not have been shared with the player.','这阵子的打算':'Current goals','还留在心里的事':'Lingering feelings','最近没有仍在持续的事件心情。':'No recent event is still affecting their mood.',
'留下的涟漪':'Ripples left behind','听说的事':'Things you have heard','还没有听到街坊的私事。':'You have not heard any private stories yet.','角色记录':'Character records','行动与情绪 / 表情由 Jev 从候选中选择，游戏执行合法后果。台词使用预写模板。':'Jev chooses actions and affect from candidates; the game applies valid consequences. Dialogue uses authored templates.','保留的 Jev 决策':'Retained Jev decisions','平均响应 ms':'Average response (ms)','等待请求':'Pending requests','本页发出请求':'Requests this session','真实 Jev':'Real Jev','规则演示（不调用模型）':'Rules demo (no model calls)','自动重试中':'Retrying automatically','切换规则演示':'Use rules demo','切换真实 Jev':'Use real Jev','重新连接':'Reconnect','导出经历 JSON':'Export history JSON','行动意图已更新':'Action intention updated','开始后记录角色的真实选择。':'Character decisions appear after you start.','情绪':'Affect',
'结束交谈，开始帮忙':'End conversation and start helping','结束交谈':'End conversation','正在斟酌你的话…':'Considering your words…','你走到身旁，对方停下了脚步。想说些什么？':'You approach, and they stop to listen. What would you like to say?','已约好帮忙，结束交谈后开始计时。':'Help agreed. The timer starts when you end the conversation.','交谈期间行人、体力和订单计时暂停。':'Residents, energy, and delivery timers pause during conversation.','随身背包':'Your bag','雾港广场':'Fog Harbor Plaza','附近服务':'Nearby services','返回街区':'Back to the neighborhood','规则演示':'Rules demo','连接 Jev…':'Connecting to Jev…','Jev 已连接':'Jev connected','等待配置':'Awaiting configuration','▶ 继续':'▶ Resume','Ⅱ 暂停':'Ⅱ Pause','生活费':'Money','健康':'Health','已站稳脚跟':'Established','目标：第三天 / 三单':'Goal: day three / three deliveries','空空的':'Empty',
'交谈期间世界停留，结束后恢复探索。':'The world pauses while you talk. End the conversation to explore.','肚子很饿了，记得吃用背包里的食物。':'You are very hungry. Eat something from your bag.','体力不足，去广场或临水亭歇脚。':'Low energy. Rest at the plaza or Riverside Pavilion.','连接恢复前，已有行动与生活继续。':'Life and existing activities continue while the connection recovers.','规则演示 · 没有调用 Jev':'Rules demo · No Jev calls','你的约定，正在成为他们的记忆。':'Your promises are becoming their memories.','无法访问本机存档，请导出经历保存。':'Cannot access local storage. Export your history to keep it.','规则演示已开启，不调用模型。':'Rules demo enabled. No model calls.','已切回真实 Jev。':'Switched to real Jev.','经历和角色记录已导出。':'History and character records exported.','第一天，从照顾好自己开始。':'Day one. Start by looking after yourself.',
'你':'You','E  交谈':'E  Talk','旅程结束 · 可以重新开始':'Journey ended · You can start again','白点是你':'The white dot is you','新增一段角色经历':'A new character experience recorded','接单 / 取餐 / 买饭':'Orders / Pickup / Food','购买面包':'Buy bread','住宿休息':'Lodging and rest','打工赚钱':'Work for pay','免费歇脚':'Free rest','E  广场长椅 · 免费歇脚':'E  Plaza bench · Free rest','雾 港 广 场':'FOG HARBOR PLAZA','↓  南 码 头':'↓ SOUTH DOCK','等候中':'Waiting','行进中':'Walking','斟酌中':'Considering',
'你的外卖到了。':'Your delivery is here.','交出对应餐品，由收件人验收并决定付款。':'Hand over the matching meal; the customer inspects it and decides payment.','抱歉送晚了，这份餐你还愿意收吗？':'Sorry I am late. Would you still like this meal?','说明耽搁并交付，对方可按约付款、减款或拒收。':'Explain the delay and deliver. They may pay in full, reduce payment, or refuse.','又见面了，今天怎么样？':'Good to see you again. How is your day?','你好，我刚搬来，认识一下吧。':'Hello, I just moved here. Nice to meet you.','向对方打招呼。':'Say hello.','最近有什么想聊的吗？':'Anything you would like to talk about?','对方可以闲聊、提出请求，或选择不谈。':'They may chat, make a request, or choose not to talk.','最近有什么自己的打算？':'Do you have any plans of your own lately?','可以聊聊个人计划，也可以选择不谈。':'They may share their personal plans or choose not to.','最近心情怎么样？':'How have you been feeling lately?','询问近来的感受，不预先假定对方经历了什么。':'Ask how they feel without assuming what they have experienced.','这里有我能帮忙做的活吗？':'Is there any work I could help with?','先问清楚具体工作与报酬，再决定是否接受。':'Ask about the work and pay before deciding whether to accept.','这份活我先不接了。':'I will pass on this job for now.','拒绝当前提议，不产生承诺或付款。':'Decline this offer without making a promise or receiving payment.','对方接受后才从背包取出这一份食物；拒绝不消耗。':'One food item leaves your bag only if accepted. Refusal costs nothing.','公开说起已知私事，附近居民可能听见，可能伤害信任。':'Mention a known private matter publicly. Nearby residents may hear, and trust may suffer.','上次当众说了你的私事，对不起。':'I am sorry I brought up your private business in public.','为公开私事道歉。对方可以接受，也可以拒绝。':'Apologize for exposing a private matter. They may accept or refuse.','上次约好回来帮忙，我却没来，对不起。':'I am sorry I promised to return and help but never came.','为爽约道歉。即使被原谅，失约经历也不会消失。':'Apologize for breaking a promise. Forgiveness does not erase what happened.'
};
export const UI_TEMPLATES: Record<string,string> = {
'已保存 · {0}':'Saved · {0}','接单：{0} · {1} 元':'Accept order: {0} · ¥{1}','备餐中 · {0} 秒':'Preparing · {0} seconds','下一批短工 · {0} 秒后':'Next job · in {0} seconds','{0} · 还需 {1} 秒':'{0} · {1} seconds remaining','吃用 {0} ×{1} · 饱腹 +{2}':'Eat {0} ×{1} · Fullness +{2}',
'第 {0} 天':'Day {0}','第 {0} 天 · {1}':'Day {0} · {1}','第 {0} 天   {1}':'Day {0}   {1}','{0} · {1} 格':'{0} · {1} tiles','站稳脚跟：活到第三天 · 配送 {0} / 3 单':'Get established: reach day three · Deliveries {0} / 3','配送成功 {0} · 未完成 {1} · 累计收入 {2} 元 / 支出 {3} 元':'Delivered {0} · Unfinished {1} · Earned ¥{2} / Spent ¥{3}',
'约 {0} 秒':'About {0} seconds','听{0}说':'Heard from {0}','{0}（旧消息）':'{0} (old report)','{0} · 第 {1} 天{2}':'{0} · Day {1}: {2}','{0}，世界已暂停。':'{0}; the world is paused.','{0} · 余 {1} 秒':'{0} · {1} seconds left','影响正在淡去 · 约 {0} 秒':'Fading influence · about {0} seconds','查看{0}':'View {0}',
'历史保留最近 180 条行动与结果；不代表全程总量。当前模式：{0}。':'History retains the latest 180 actions and outcomes, not the lifetime total. Current mode: {0}.','{0} ms · 情绪 {1}':'{0} ms · Affect {1}','你：{0}':'You: {0}','{0} 次配送 · {1}':'{0} deliveries · {1}','你生活到第 {0} 天，完成 {1} 次配送。下次记得及时吃饭和休息。':'You reached day {0} and completed {1} deliveries. Next time, remember to eat and rest.',
'约 {0} 步':'About {0} steps','E  查看{0}':'E  View {0}','E  向{0}交付外卖':'E  Deliver to {0}','E  与收件人{0}交谈':'E  Talk to customer {0}','E  与{0}交谈':'E  Talk to {0}',
'我回来{0}了。':'I am back to {0}.','我现在就来{0}。':'I will {0} now.','工作 {0} 秒，完成后获得 {1} 元；中止不付报酬。':'Work for {0} seconds and receive ¥{1} on completion. No pay if canceled.','我在 {0} 秒内回来{1}，可以吗？':'Can I return within {0} seconds to {1}?','请求约定：{0} 秒内回来开始工作，完成后获得 {1} 元；对方同意后才生效。':'Propose returning within {0} seconds to start work, earning ¥{1} on completion. The agreement takes effect only if accepted.','这份{0}给你，要吗？':'Would you like this {0}?','当街提起：{0}':'Mention publicly: {0}'
};
Object.assign(UI_EN,{
'缺少服务端密钥':'Server API key missing','本地服务未连接':'Local server disconnected','刚才的交互条件已变化，请重新选择。':'The interaction conditions changed. Please choose again.','本次调用额度已用完':'Session budget exhausted','OpenRouter 余额不足':'Insufficient OpenRouter credit','密钥验证失败':'API key verification failed','Jev 连接暂时中断':'Jev connection interrupted','角色正在等候回复，稍后自动重试；世界仍暂停，也可以结束交谈。':'Waiting for a reply; retrying shortly. The world remains paused. You can end the conversation.','角色正在等候回复，稍后自动重试；你可以继续行动。':'Waiting for a reply; retrying shortly. You can continue exploring.'
});
Object.assign(UI_TEMPLATES,{
'{0}，可在角色记录中重连。世界仍暂停，结束交谈后恢复。':'{0}. Reconnect in Character records. The world stays paused until you end the conversation.',
'{0}，可在角色记录中重连。已有动作继续执行。':'{0}. Reconnect in Character records. Existing activities continue.'
});
Object.assign(UI_TEMPLATES,{
'{0} 秒':'{0} seconds','第 {0} 天 · {1} 秒':'Day {0} · {1} seconds'
});
Object.assign(UI_EN,{
'等你重新说起具体事情':'Waiting for you to choose a specific topic again',
'旧存档的谈话需要重新选择具体事项。':'This conversation from an older save needs a specific topic selected again.',
'这段闲谈缺少双方同意或与别的活动冲突，先停下来。':'This chat lacks mutual consent or conflicts with another activity, so it has stopped.'
});
Object.assign(UI_TEMPLATES,{
'E  {0}':'E  {0}','{0} — completed.':'{0} — completed.'
});
Object.assign(UI_EN,{'背包与订单已结算。':'Your bag and order have been settled.'});
